package rentMotorbike.services;

import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;

import rentMotorbike.Client;

 public class PersonDBManager {

	private Connection connect;
	private Statement stat;
	private PreparedStatement addClientStat;
	private PreparedStatement getClientsStat;
	
	
	public PersonDBManager(){
		
		try {
		 Properties props=new Properties();
			
		 try {
		  props.load(ClassLoader.getSystemResourceAsStream("jdbc.properties"));
	         }
		    catch (IOException e){
			  e.printStackTrace();
             }
			
			connect = DriverManager.getConnection(props.getProperty("url"));
			stat=connect.createStatement();
			boolean clientTableExists=false;
		 	
			ResultSet rs= connect.getMetaData().getTables(null, null, null, null);
			
			while(rs.next()){
				if("Client".equalsIgnoreCase(rs.getString("TABLE_NAME"))){
					clientTableExists=true;
						break;
					}
			}
			
			
			if(!clientTableExists){
				stat.executeUpdate("" +
					"CREATE TABLE client(" +
					"id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
					"name varchar(20)," +
					"" +
					")");
		          }
			
	             addClientStat=connect.prepareStatement("" +
			        "INSERT INTO client (name) VALUES (?)" + "");
			
			     getClientsStat=connect.prepareStatement("" +
					"SELECT * FROM client" + "");
			
	                  } 
		         catch (SQLException e) {
			        e.printStackTrace(); 
		          }
	    	}
	
	public void addClient(Client p){
		try {
		  addClientStat.setString(1, p.getName());
		  addClientStat.executeUpdate();
			} 
		   catch (SQLException e) {
			  e.printStackTrace();
		    }
	    }
	
	public List<Client> getAllClients(){
		List<Client> clients=new ArrayList<Client>();
		
		try {
		  ResultSet rs= getClientsStat.executeQuery();
			while(rs.next())
			{
				clients.add(new Client(rs.getString("name"), null, null));
			}
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return clients;
	}
	
	
}
